export { default as SearchSvg } from './Icons/search.svg?react';
export { default as User } from './Icons/User.svg?react';
export { default as Cart } from './Icons/cart.svg?react';
export { default as LanguageIcon } from './Icons/language.svg?react';
export { default as Activity } from './Icons/activity.svg?react';
export { default as Plan } from './Icons/plan.svg?react';
export { default as Eating } from './Icons/eating.svg?react';
export { default as CircleArrow } from './Icons/clarity_circle-arrow-solid.svg?react';
export { default as Pin } from './Icons/pin.svg?react';
export { default as GoldMetal } from './Icons/Gold Medal.svg?react';
export { default as GoldStar } from './Icons/goldStar.svg?react';
export { default as Checkcircle } from './Icons/check-circle.svg?react';
export { default as VerifiedProfile } from './Icons/Verified Check.svg?react';
export { default as ImportUrl } from './Icons/ImportUrl.svg?react';
export { default as ImportYoutupe } from './Icons/youtupe.svg?react';
export { default as Importtikto } from './Icons/tiktok.svg?react';
export { default as ImportInsta } from './Icons/insta.svg?react';
export { default as Calories } from './Icons/Calories.svg?react';
export { default as Carbohydrates } from './Icons/Carbohydrates.svg?react';
export { default as Protein } from './Icons/Protein.svg?react';
export { default as TotalFat } from './Icons/Total Fat.svg?react';
export { default as Sugers } from './Icons/Sugers.svg?react';
export { default as Clothes } from './Icons/clothes 1.svg?react';
export { default as G555 } from './Icons/g555.svg?react';
export { default as Muscle} from './Icons/muscle 1.svg?react';
export { default as Weightloss} from './Icons/weight-loss 1.svg?react';
export { default as Lightning} from './Icons/Lightning.svg?react';
export { default as Bread} from './Icons/bread 1.svg?react';
export { default as Proteins} from './Icons/proteins 1.svg?react';
export { default as BalancedPlan} from './Icons/Balanced Plan.svg?react';
export { default as Toast} from './Icons/toast.svg?react';
export { default as Fish} from './Icons/fish.svg?react';
export { default as Water} from './Icons/water.svg?react';
export { default as Fire} from './Icons/Fire.svg?react';
export { default as CheckIcon} from './Icons/checkIcon.svg?react';
export { default as Search} from './Icons/search-normal.svg?react';
export { default as GoalDashboardVector1} from './Icons/GoalDashboardVector1.svg?react';
export { default as GoalDashboardVector2} from './Icons/GoalDashboardVector2.svg?react';
export { default as GoalDashboardVector3} from './Icons/GoalDashboardVector3.svg?react';
export { default as Chevrondown} from './Icons/chevron-down.svg?react';
export { default as Bell} from './Icons/bell.svg?react';
export { default as Message} from './Icons/message.svg?react';
export { default as GoalDashboardVector4} from './Icons/GoalDashboardvector4.svg?react';
export { default as Facebook} from './Icons/Facebook.svg?react';
export { default as Instagram} from './Icons/Instagram.svg?react';
export { default as Tiwtter} from './Icons/Tiwtter.svg?react';
export { default as Youtube} from './Icons/Youtube.svg?react';
export { default as TiktokIcon} from './Icons/tiktokIcon.svg?react';
export { default as Xtwetter} from './Icons/xtwetter.svg?react';
export { default as Nutrationres3} from './Icons/nutrationres3.svg?react';
export { default as Nutrationres4} from './Icons/nutrationres4.svg?react';
export { default as Check} from './Icons/check.svg?react';
export { default as Website} from './Icons/website.svg?react';
export { default as InstagramIcon} from './Icons/instagramIcon.svg?react';
export { default as Dish} from './Icons/Dish.svg?react';
export { default as Bookmark} from './Icons/Bookmark.svg?react';
export { default as Goals} from './Icons/Goals.svg?react';
export { default as EditProfile} from './Icons/EditProfile.svg?react';
export { default as AccSetting} from './Icons/AccSetting.svg?react';
export { default as Plus} from './Icons/Plus.svg?react';
export { default as Chat} from './Icons/Chat.svg?react';
export { default as Voice} from './Icons/Voice.svg?react';
export { default as Video} from './Icons/Video.svg?react';
export { default as Calender} from './Icons/Calender.svg?react';
export { default as Star} from './Icons/Star.svg?react';
export { default as Patient} from './Icons/Patient.svg?react';
export { default as Rate} from './Icons/rate.svg?react';
export { default as Chart} from './Icons/Chart.svg?react';
export { default as Comment} from './Icons/Comment.svg?react';
export { default as Globel} from './Icons/globel.svg?react';
export { default as Translation} from './Icons/Translation.svg?react';
export { default as SeeMore} from './Icons/seeMore.svg?react';
export { default as VoiceMsg} from './Icons/VoiceMsg.svg?react';
export { default as Typing} from './Icons/Typing.svg?react';
export { default as Send} from './Icons/Send.svg?react';
export { default as Attached} from './Icons/attached.svg?react';
export { default as MuteMic} from './Icons/muteMic.svg?react';
export { default as Sound} from './Icons/Sound.svg?react';
export { default as Upload} from './Icons/Upload.svg?react';
export { default as Ring} from './Icons/ring.svg?react';
export { default as Camera} from './Icons/camera.svg?react';
export { default as Setting} from './Icons/Setting.svg?react';
export { default as fullscreen} from './Icons/fullscreen.svg?react';
export { default as SaveIcon} from './Icons/SaveIcon.svg?react';
export { default as SeachGrey} from './Icons/SeachGrey.svg?react';
export { default as Image} from './Icons/image.svg?react';
export { default as File} from './Icons/File.svg?react';
export { default as Contact} from './Icons/contact.svg?react';
export { default as Location} from './Icons/location.svg?react';
export { default as Call} from './Icons/call.svg?react';
export { default as FacebookIcon} from './Icons/facebookIcon.svg?react';
export { default as Google} from './Icons/google.svg?react';